name: volet_roulant_app
description: A smart roller shutter control app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP and Storage
  http: ^1.2.2
  shared_preferences: ^2.3.0

  # State Management
  provider: ^6.1.2

  # Date and Formatting
  intl: ^0.19.0

  # UI and Animation
  flutter_material_color_picker: ^1.2.0
  speech_to_text: ^7.0.0
  flutter_animate: ^4.5.0
  vibration: ^2.0.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  animated_background: ^2.0.0
  weather_icons: ^3.0.0

  # Notifications
  flutter_local_notifications: ^17.2.3 # Downgraded for stability with current setup

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  firebase_analytics: ^11.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

