// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISA1z3ytCObWPoG0T36TwjZd45J1gSms',
    appId: '1:1057565846889:web:60e3056519a8543115a1f8',
    messagingSenderId: '1057565846889',
    projectId: 'voletroulantcontrol',
    authDomain: 'voletroulantcontrol.firebaseapp.com',
    databaseURL: 'https://voletroulantcontrol-default-rtdb.firebaseio.com',
    storageBucket: 'voletroulantcontrol.firebasestorage.app',
    measurementId: 'G-6LEK3ZMEDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrS0oyyS5kYMizS3OQTA5ikgk5DmGXytg',
    appId: '1:1057565846889:android:be57ec73023cde6f15a1f8',
    messagingSenderId: '1057565846889',
    projectId: 'voletroulantcontrol',
    databaseURL: 'https://voletroulantcontrol-default-rtdb.firebaseio.com',
    storageBucket: 'voletroulantcontrol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtQVK0OFnLTR6c-i1p2sBUJLNlG0fW52Y',
    appId: '1:1057565846889:ios:961b4ca6915e6e6a15a1f8',
    messagingSenderId: '1057565846889',
    projectId: 'voletroulantcontrol',
    databaseURL: 'https://voletroulantcontrol-default-rtdb.firebaseio.com',
    storageBucket: 'voletroulantcontrol.firebasestorage.app',
    iosClientId: '1057565846889-4v7n8rug3vtq6l7g431tbb77jqka4o13.apps.googleusercontent.com',
    iosBundleId: 'com.example.voletRoulantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtQVK0OFnLTR6c-i1p2sBUJLNlG0fW52Y',
    appId: '1:1057565846889:ios:961b4ca6915e6e6a15a1f8',
    messagingSenderId: '1057565846889',
    projectId: 'voletroulantcontrol',
    databaseURL: 'https://voletroulantcontrol-default-rtdb.firebaseio.com',
    storageBucket: 'voletroulantcontrol.firebasestorage.app',
    iosClientId: '1057565846889-4v7n8rug3vtq6l7g431tbb77jqka4o13.apps.googleusercontent.com',
    iosBundleId: 'com.example.voletRoulantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCISA1z3ytCObWPoG0T36TwjZd45J1gSms',
    appId: '1:1057565846889:web:6a1f1be3b3cf9ad315a1f8',
    messagingSenderId: '1057565846889',
    projectId: 'voletroulantcontrol',
    authDomain: 'voletroulantcontrol.firebaseapp.com',
    databaseURL: 'https://voletroulantcontrol-default-rtdb.firebaseio.com',
    storageBucket: 'voletroulantcontrol.firebasestorage.app',
    measurementId: 'G-NTXLXW60B7',
  );
}
